
version: '3'
services:
  rrdb:
    environment: 
        POSTGRES_USER: postgres
        POSTGRES_PASS: readingroom
        POSTGRES_DBNAME: readingroom
    image: postgres:11-alpine
    ports:
    - "5432"
    volumes:
      - rr-data:/var/lib/postgresql/data
    networks:
      - back

  web:
    restart: always
    image: readingroom_site
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    links:
      - rrdb
    ports:
      - "8000"
    volumes:
      # - ./web/app:/home/django/app
      - rr-static:/var/www/html/static
      - rr-media:/var/www/html/media
    networks:
      - front
      - back

volumes:
  rr-data:
  rr-media:
  rr-static:

networks:
  front:
  back:

