
version: '3'
services:
  rrdb:
    environment: 
        - POSTGRES_USER
        - POSTGRES_PASSWORD
        - POSTGRES_DB
    image: ${POSTGRES_IMAGE}
    ports:
    - "${POSTGRES_PORT}:5432"
    volumes:
      - rr-data:/var/lib/postgresql/data
      - ../readingroom-site-db:/source
    networks:
      - back

  web:
    restart: always
    image: readingroom_site
    # build: 
    #   context: .
    #   dockerfile: Dockerfile
    links:
      - rrdb
    ports:
      - "8000"
    volumes:
      # - ./web/app:/home/django/app
      - rr-static:/var/www/html/static
      - rr-media:/var/www/html/media
    networks:
      - front
      - back

volumes:
  rr-data:
  rr-media:
  rr-static:

networks:
  front:
  back:

